/******************************************************
 * ArchC Resources implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include  "rs08_arch.H"
#include  "rs08_arch_ref.H"

//!/Default constructor.
rs08_arch_ref::rs08_arch_ref(rs08_arch& arch) : ac_arch_ref<rs08_parms::ac_word, rs08_parms::ac_Hword>(arch),
  ac_pc(arch.ac_pc),
  RAM(arch.RAM),   A(arch.A),   CCR(arch.CCR),   PC(arch.PC),   SPC(arch.SPC) {}

