/******************************************************
 * ArchC Resources Implementation file.               *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

#include "rs08_arch.H"

rs08_arch::rs08_arch() :
  ac_arch_dec_if<rs08_parms::ac_word, rs08_parms::ac_Hword>(rs08_parms::AC_MAX_BUFFER),
  ac_pc("ac_pc", 0),
  RAM_stg("RAM_stg", 16384U),
  RAM(*this, RAM_stg),
  A("A", 0),
  CCR("CCR"),
  PC("PC"),
  SPC("SPC") {

  ac_mt_endian = rs08_parms::AC_MATCH_ENDIAN;
  ac_tgt_endian = rs08_parms::AC_PROC_ENDIAN;

  IM = &RAM;
  APP_MEM = &RAM;

}

