/******************************************************
 * This is the main file for the rs08 ArchC model     *
 * This file is automatically generated by ArchC      *
 * WITHOUT WARRANTY OF ANY KIND, either express       *
 * or implied.                                        *
 * For more information on ArchC, please visit:       *
 * http://www.archc.org                               *
 *                                                    *
 * The ArchC Team                                     *
 * Computer Systems Laboratory (LSC)                  *
 * IC-UNICAMP                                         *
 * http://www.lsc.ic.unicamp.br                       *
 ******************************************************/
 

const char *project_name="rs08";
const char *project_file="rs08.ac";
const char *archc_version="2.0";
const char *archc_options="-abi ";

#include  <iostream>
#include  <systemc.h>
#include  "ac_stats_base.H"
#include  "rs08.H"



int sc_main(int ac, char *av[])
{

  //!  ISA simulator
  rs08 rs08_proc1("rs08");

#ifdef AC_DEBUG
  ac_trace("rs08_proc1.trace");
#endif 

  rs08_proc1.init(ac, av);
  cerr << endl;

  sc_start(-1);

  rs08_proc1.PrintStat();
  cerr << endl;

#ifdef AC_STATS
  ac_stats_base::print_all_stats(std::cerr);
#endif 

#ifdef AC_DEBUG
  ac_close_trace();
#endif 

  return rs08_proc1.ac_exit_status;
}
