#acsim mips1.ac -abi
#make -f Makefile.archc
#mips1.x --load=<nome do programa que você quer executar> <parâmetros para o pro#grama>

all:
	/home/Tiago/Desktop/archc-2.0/src/acsim/acsim rs08.ac -abi
	make -f Makefile.archc

add:
	./rs08.x --load=teste.c
